language = {'polish':  {'title': 'Kółko i krzyżyk',
                        'difficulty': 'Poziom trudności',
                        'sign': 'Znak',
                        'change': 'Zmień',
                        'easy': 'Łatwy',
                        'medium': 'Średni',
                        'hard': 'Trudny',
                        'expert': 'Ekspert',
                        'unbeatable': 'Niezwyciężony',
                        'start': 'Start',
                        'lost': 'Przegrana',
                        'win': 'Wygrana',
                        'tie': 'Remis',
                        'again': 'Ponów',
                        'menu': 'Menu',
                        'language': 'Język',
                        'current_language': 'polski'},
            'english': {'title': 'Tic Tac Toe',
                        'difficulty': 'Difficulty level ',
                        'sign': 'Sign',
                        'change': 'Change',
                        'easy': 'Easy',
                        'medium': 'Medium',
                        'hard': 'Hard',
                        'expert': 'Expert',
                        'unbeatable': 'Unbeatable',
                        'start': 'Start',
                        'lost': 'You lost',
                        'win': 'You won',
                        'tie': 'Tie',
                        'again': 'Again',
                        'menu': 'Menu',
                        'language': 'Language',
                        'current_language': 'english'},
            }
