language = {'polish':  {'title': 'Kółko i krzyżyk',
                        'difficulty': 'Poziom trudności',
                        'sign': 'Znak',
                        'change_sign': 'Zmień znak',
                        'change_difficulty': 'Zmień trudność',
                        'easy': 'Łatwy',
                        'medium': 'Średni',
                        'hard': 'Trudny',
                        'expert': 'Ekspert',
                        'start': 'Start',
                        'lost': 'Przegrana',
                        'win': 'Wygrana',
                        'tie': 'Remis',
                        'again': 'Ponów',
                        'menu': 'Menu',
                        'language': 'Zmień język'},
            'english': {'title': 'Tic Tac Toe',
                        'difficulty': 'Difficulty level',
                        'sign': 'Sign',
                        'change_sign': 'Change sign',
                        'change_difficulty': 'Change difficulty',
                        'easy': 'Easy',
                        'medium': 'Medium',
                        'hard': 'Hard',
                        'expert': 'Expert',
                        'start': 'Start',
                        'lost': 'You lost',
                        'win': 'You won',
                        'tie': 'Tie',
                        'again': 'Again',
                        'menu': 'Menu',
                        'language': 'Change language'},
            }
